### ISSUE TITLE
Issue with HMIS data not matching HMIS_CSV data

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/PIT_HIC#11]
https://github.com/timbender-ncceh/PIT_HIC/blob/aeadf39bc14dfc7aefe7c6722d14d5c081ecd1de/pit_survey_calculations.R#L756-L781

## ZenDesk Guide ##
See ZenDesk Guide [here](https://ncceh.zendesk.com/hc/en-us/articles/7218387528723-Using-the-History-Color-Bar-to-View-and-Edit-Prior-Responses)

## Example PIDs from Spot Check ##
PID	issues?
369990	FALSE
413124	FALSE
423512	FALSE
447081	FALSE
454866	FALSE
466941	FALSE
1011237	FALSE
1024263	FALSE
1025126	FALSE
1032513	FALSE
1034153	FALSE
1036767	FALSE
1037465	FALSE
1039556	FALSE
1040104	FALSE
433524	TRUE
1016309	TRUE

**Comment by timbender-ncceh** [comment]
code to spot-check PersonalIDs in "spot_check_race_HMIS.R" (local)

**Comment by andreaNCCEH** [comment]
Troubleshooting suggestion: For 433524 and 1016309, look up their profiles in HMIS, review the history of who entered different Client Demographics like race, and determine if those projects (providers creating) are included in the BoS Unsheltered PIT Reporting Group used for the PIT report.
It's possible the missing data was added by projects that aren't included in the dataset.

**Comment by timbender-ncceh** [comment]
Andrea wrote in chat this evening: 

> Last minute random thought - for race issue, the issue could be in our code cleaning the data or in the export itself
> Or not a problem at all if the projects entering black aren’t supposed to be included in the report.
> Just thought it might be helpful to outline those 3 possibilities.
> Anyways, have a good night!

**Comment by andreaNCCEH** [comment]
- [ ] Confirm if Clients with different race in hmis vs csv export had data entered by projects outside of the Unsheltered BOS Reporting group
- [ ] If entered by projects included in Unsheltered BoS Reporting group, identify sample clients and draft ticket to send Wellsky for CSV export error

**Comment by timbender-ncceh** [comment]
Cannot reproduce the issue despite copious notes and examples; must've just been a goblin
