### ISSUE TITLE
Issue with how this function logically handles inputs when returning Unaccompanied youth - households without children.  See notes below. 

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/PIT_HIC#14]
https://github.com/timbender-ncceh/PIT_HIC/blob/4e60a27235aa2f3d3a6469ecd429c810809189cf/pit_survey_calculations.R#L65-L71

This will be resolved by resolving issues #15 and #16
## Problem: ##
the logic seems wonky for "YOUTH - Unaccompanied youth - households without children"
: I see three households with folks over 24 in them

## HHids with problems: ##
h_1173052, 
h_1174754, 
h_1188389

**Comment by andreaNCCEH** [comment]
Tim added an image with two potential issues form revised code for this section
![image (19)](https://user-images.githubusercontent.com/67340114/227960822-0a3e22cf-1448-41b4-939a-22e6d9f15156.png)

Andrea: I'd have to see the output details but I'm not sure #8 is a problem>
A household without children (over 18), unaccompanied youth (under 24), and Veteran is possible. I think that means a household with like a 20 year old vet. 
You could check out the individuals pulled into that category to be sure.

For #9, similar thing. I think it's possible that a household with a 22 year old youth would be labeled as Youth, household without children, unaccompanied youth. 
Again, take a look at the individuals and see if they're aged 18-24.

**Comment by timbender-ncceh** [comment]
I'm going to close this issue for now.  we can open again in the future if we find circumstances where logic isn't working as planned.  To summarise, the age thing is logically OK.  for now.

**Comment by andreaNCCEH** [comment]
I still see some issues:

- [ ] Children under 17 labeled as household without children
- [ ] Children under 17 with "Child" as Rel to HoH labeled as unaccompanied Youth


Examples:
![Unaccompanied Youth that should maybe be in a Parenting Youth HH](https://user-images.githubusercontent.com/67340114/229140977-137596ee-7f7c-4575-ad45-0b116aac0413.png)

**Comment by andreaNCCEH** [comment]
Maybe I just need to be reminded on the definition or crosswalk of the different YV_hh_type categories

**Comment by timbender-ncceh** [comment]
There is a 1032029 (personalid), age = 4, but hhType_df = "hh without children".  WITHOUT CHILDREN!!!!

see other examples in andrea's comment above.

**Comment by timbender-ncceh** [comment]
fixed logical issue in function.
