### ISSUE TITLE
Current Living Situtation applied to wrong client

### ISSUE THREAD

**Issue by andreaNCCEH** [timbender-ncceh/PIT_HIC#28]
I was looking for DQ issues with disabling conditions that I could fix in order to increase CH status and found a client who should not have the CLS they are listed with. Here are some steps to begin to scope out if there's a bigger issue:

- [ ] Open Client Profile 1016284 in HMIS and look at Entry Exit tab. If you go to the Pencils (any) you can see there is no CLS for 1/25 anywhere. 
- [ ] Search for client 1016284 in the original input Current Living Situation table and confirm with Andrea if the CLS is 1/25 place not meant for habitation
- [ ] Create summary table of clients where "EntryDate" is after "hh_cls_infodate"
- [ ] Create export so the individual clients can be reviewed
- [ ] Check 3-5 clients in HMIS to see if CLS was entered for them for CLS date 1/25/23 or if there's no CLS date
- [ ] Share summary table, export, and results of client checks here

**Comment by andreaNCCEH** [comment]
OMG I can't read! The entry date is 2/28/22!! Not an issue

**Comment by timbender-ncceh** [comment]
andrea noted that this issue was opened in error and it's not an issue at all.  but in the process she learned how to open an issue, so not all was lost 🥇
