### ISSUE TITLE
logic underlying function py_18.24() (calculates parenting youth ages 18-24) is broken. 

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/PIT_HIC#30]
https://github.com/timbender-ncceh/PIT_HIC/blob/4982a6b68c387f94a80940c24263af892c787ccf/working_files/pit_survey_calculations.R#L86-L114

## example failure ##
![image](https://user-images.githubusercontent.com/105810134/229789922-d50c96bc-ece6-4d79-b7dd-a09cd1b196a3.png)

ages: c(19, 4)
rel2hoh: c("Self (head of household)", "Head of household's Child")
RETURNS: 
[1] FALSE

**Comment by timbender-ncceh** [comment]
fixed logical issue in function.

**Comment by andreaNCCEH** [comment]
For the Unsheltered Count, I don't see any clients where py1_18.24 = "TRUE"
Here are the clients I found that I think should be TRUE

1035758 (24 with child age 5)
1036035 (21 with child age 0)
